[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "plone.htmx"
version = "0.2.0.dev0"
description = "HTMX support in Plone"
readme = "README.rst"
license = {text = "GNU General Public License v3"}
authors = [
    {name = "Godefroid Chapelle", email = "gotcha@bubblenet.be"},
]
keywords = ["plone", "htmx"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: Plone",
    "Framework :: Plone :: 6.1",
]
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
docs = ["sphinx", "furo"]
tests = [
    "pytest",
    "pytest-plone>=0.5.0",
    "plone.app.testing",
    "plone.testing",
]

[project.urls]
Homepage = "https://github.com/plone/plone.htmx"
"Bug Tracker" = "https://github.com/plone/plone.htmx/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["plone*"]

[tool.setuptools.package-data]
"plone.htmx" = [
    "static/*",
    "profiles/**/*",
    "browser/**/*.pt",
    "browser/**/*.zcml",
    "*.zcml",
    "*.xml",
]

[tool.pytest.ini_options]
testpaths = ["plone/htmx/tests"]
