name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Cache eggs
        uses: actions/cache@v1.2.0
        with:
          path: eggs
          key: ubuntu-2.7-eggs
      - name: Buildout
        run: |
          pip install -r requirements_dev.txt
          buildout -Nv extends=https://dist.plone.org/release/5.1.7/versions.cfg
      - name: Run Zope
        run: |
          bin/instance start
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 120
          spec: cypress/integration/edit_title.spec.js
